# Actions -> Python application
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# https://crontab.guru/
# 한국 11시면 cron에 11-9=2로 표현 
# 한국 22시면 22-9 = 13 
# 5분이라 걸어놓음 10분 후 쯤 15분에 알람 옴
# cron순서 - 분 시

name: Python application

on:
  schedule:
    #- cron : '0 * * * *'   # 매일 정시에 실행
    #- cron : '0 */2 * * *' # 매일 2시간 간격으로 정시에 실행
    - cron : '0 23 * * 1-5' # 주말을 제외한(1-5) 매일 8시 실행
    - cron : '0 0-10/3 * * 1-5' # 주말을 제외한(1-5) 매일 10~19시 사이 3시간 간격으로 실행
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.1
      - name: Install dependencies

        run: |
          python -m pip install --upgrade pip
          pip install requests==2.27.1 bs4==0.0.1 python-telegram-bot==13.14 schedule

      - name: samsungcardbot
        run: |
          python newsKeywordBot.py

# 마지막 줄입니다.
